# Generated by Django 2.0.1 on 2018-01-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180126_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, max_length=200, upload_to='uploads/'),
        ),
    ]
