# Generated by Django 2.0.1 on 2018-01-26 02:39

from django.db import migrations
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180126_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=django_thumbs.db.models.ImageWithThumbsField(upload_to='uploads/'),
        ),
    ]
