# Generated by Django 2.0.1 on 2018-01-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180126_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='文件缩略图'),
        ),
    ]
